export const productsApi: string[] = [
    "Vibrant Batik Masterpiece - Southeast Asian Artistry, Timeless Style",
    "Handcrafted Batik Heritage - Wearable Art, Stories Woven Boldly",
    "Intricate Batik Fabric - Southeast Asian Artistry, A Touch of Luxury",
    "Support Artisan Excellence - Unique Batik Fabric, Empowering Tradition",
    "Taste of the Tropics - Sun-Kissed Fruit Preserves, Crafted Locally",
    "Exotic Fruit Fusion - Bursting with Southeast Asian Flavors, Farm-Fresh Preserves",
    "Island Orchard in a Jar - Tropical Fruit Preserves, Natural Sweetness",
    "Farm-to-Table Freshness - Premium Southeast Asian Fruit Preserves",
    "Handmade Earthenware Mug - Simple Elegance, Locally Crafted",
    "From the Earth, For Your Home - Artisan Clay Mug, Southeast Asian Tradition",
    "Everyday Ritual Redefined - Handcrafted Clay Mug, Locally Made with Care",
    "Support Local Talent - Unique Clay Pottery Mug, Masterful Creation",
    "Southeast Asian Wellness Blend - Organic Herbal Tea, Crafted for Tranquility",
    "Soothing Botanicals - Local Herb-Infused Tea, Restore & Refresh",
    "Island Botanical Harmony - Organic Herbal Tea Blend, Moments of Bliss",
    "Local Herb Infusion - Soothing Tea Blend, Taste of Southeast Asia",
    "Lush Tropical Paradise - Luxurious Spa Soap, Natural Ingredients",
    "Exotic Flower Bouquet - Handpicked Floral Tea, Fragrant Delight",
    "Soothing Aromatherapy Haven - Natural Essential Oil Blend, Serene Southeast Asian Scents",
    "Handcrafted Bamboo Basket - Sustainable Storage Solution, Artisan Craftsmanship",
    "Eco-Friendly Bamboo Utensils - Sustainable Dining, Southeast Asian Style",
    "Artisanal Spice Set - Bold Flavors from Southeast Asia, Culinary Adventure",
    "Traditional Handwoven Basket - Authentic Craftsmanship, Functional Beauty",
    "Tropical Oasis Reed Diffuser - Aromatic Ambiance, Southeast Asian Fragrances",
    "Sustainable Rattan Furniture Set - Eco-Chic Living, Handcrafted Comfort",
    "Artisanal Coconut Bowl Set - Natural Tableware, Sustainable Style",
    "Handwoven Pandan Basket - Eco-Friendly Storage, Southeast Asian Charm",
    "Exotic Fruit Salad Bowl - Vibrant Tableware, Fresh Flavors of Southeast Asia",
    "Eco-Conscious Bamboo Toothbrush Set - Sustainable Oral Care, Natural Beauty",
    "Tropical Fruit Salad Servers - Eco-Friendly Dining, Southeast Asian Flair",
    "Authentic Coconut Shell Candle - Island-Inspired Ambiance, Eco-Friendly Glow",
    "Handcrafted Rattan Wall Art - Sustainable Decor, Artisanal Elegance",
    "Tropical Rainforest Soap Set - Natural Skincare, Refreshing Cleansing",
    "Eco-Friendly Banana Leaf Placemat Set - Sustainable Dining, Southeast Asian Vibes",
    "Artisanal Silk Scarf - Luxurious Fashion, Southeast Asian Elegance",
    "Handwoven Seagrass Basket - Eco-Chic Storage, Coastal Charm",
    "Sustainable Bamboo Cutting Board - Eco-Friendly Kitchen, Southeast Asian Style",
    "Tropical Paradise Scented Candle - Island Escape, Aromatic Tranquility",
    "Handcrafted Coconut Shell Bowl - Sustainable Tableware, Island Charm",
    "Southeast Asian Spice Blend - Exotic Flavors, Culinary Adventure",
    "Eco-Conscious Jute Tote Bag - Sustainable Shopping, Natural Style",
    "Tropical Fruit Infusion Pitcher - Refreshing Beverages, Southeast Asian Flavors",
    "Handwoven Palm Leaf Basket - Sustainable Storage, Tropical Elegance",
    "Sustainable Bamboo Serving Tray - Eco-Friendly Entertaining, Southeast Asian Flair",
    "Exotic Floral Bath Bomb Set - Aromatic Bathing Experience, Southeast Asian Luxury",
    "Eco-Friendly Seagrass Rug - Sustainable Flooring, Coastal Comfort"
];
